# Generated by Django 3.1.7 on 2021-04-02 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_watching'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watching',
            options={'ordering': ['-date']},
        ),
    ]
