# Generated by Django 3.1.7 on 2021-04-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210402_0329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Va',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='vas',
            field=models.ManyToManyField(to='main_app.Va'),
        ),
    ]
